### ISSUE TITLE
Implement `base_helper.ts`

### ISSUE THREAD

**Issue by orkunkl** [InterWasm/DAO#26]
We have been copy-pasting common code for `helper.ts`. Let's create a `base_helper.ts` that contains shared code and use it like:

```shell
npx @cosmjs/cli@0.26 --init .../base_helper.ts --init .../cw20-base/helper.ts
```

**Comment by findolor** [comment]
https://github.com/CosmWasm/cw-plus/pull/522

**Comment by findolor** [comment]
https://github.com/CosmWasm/cw-plus/pull/535
